part020_normalize_features.py: part020_normalize_features.ipynb part010_splitting_the_data.py
	python -m jupyter nbconvert --to script $<

part010_splitting_the_data.py: part010_splitting_the_data.ipynb
	python -m jupyter nbconvert --to script $<
